// src/components/app/EditorLeftPanel.vue
<script setup>
import { ref } from 'vue';
import BrainholeInputPanel from './BrainholeInputPanel.vue';
import StageIndicator from '../StageIndicator.vue';

const activeTab = ref('brainhole');

defineProps({
  isCollapsed: {
    type: Boolean,
    default: false,
  },
  storyStart: {
    type: String,
    default: '',
  },
  windVaneFile: {
    type: Object,
    default: null,
  },
  isLoading: {
    type: Boolean,
    default: false,
  },
  dnaAssetReferences: {
    type: Object,
    default: () => ({ brainhole: [], guide: [], outline: [] }),
  },
  dnaResultReferences: {
    type: Object,
    default: () => ({ brainholeOptions: [], guide: [], architecture: [] }),
  },
  stage: {
    type: String,
    default: 'brainhole',
  },
  activeStageView: {
    type: String,
    default: 'brainhole',
  },
  fileTextIconPaths: {
    type: Array,
    default: () => [],
  },
  canCopyBody: {
    type: Boolean,
    default: false,
  },
  promptAutomationSettings: {
    type: Object,
    default: () => ({
      autoGeneratePlot: true,
      autoGenerateChoices: true,
      generateBodyBeforeChoices: true,
    }),
  },
  copySelectedChoicesWithBody: {
    type: Boolean,
    default: false,
  },
  copyBodyPreviewText: {
    type: String,
    default: '',
  },
});

const emit = defineEmits([
  'toggle-panel',
  'update:storyStart',
  'choose-wind-vane-file',
  'wind-vane-file-change',
  'wind-vane-file-dragover',
  'wind-vane-file-dragleave',
  'wind-vane-file-drop',
  'clear-wind-vane-file',
  'clear-brainhole-input',
  'generate-brainhole',
  'navigate-stage',
  'update-prompt-automation-setting',
  'copy-body',
  'update:copySelectedChoicesWithBody',
]);

function updateCopySelectedChoicesWithBody(event) {
  emit('update:copySelectedChoicesWithBody', event.target.checked);
}

function updatePromptAutomationSetting(key, event) {
  emit('update-prompt-automation-setting', key, event.target.checked);
}
</script>

<template>
  <aside class="panel panel-left" :class="{ collapsed: isCollapsed }">
    <button
      class="panel-toggle"
      type="button"
      :aria-expanded="(!isCollapsed).toString()"
      :aria-label="isCollapsed ? '展开左侧区域' : '折叠左侧区域'"
      @click="emit('toggle-panel')"
    >
      <svg class="panel-toggle-icon" viewBox="0 0 20 20" aria-hidden="true">
        <path
          v-if="isCollapsed"
          d="M7.5 4.5 13 10l-5.5 5.5"
        />
        <path
          v-else
          d="M12.5 4.5 7 10l5.5 5.5"
        />
      </svg>
    </button>

    <div v-if="isCollapsed" class="panel-collapsed-hint"></div>
    <div v-else class="panel-body">
      <div class="left-panel-tabs" role="tablist" aria-label="左侧功能区">
        <button
          class="left-panel-tab"
          :class="{ active: activeTab === 'brainhole' }"
          type="button"
          role="tab"
          :aria-selected="(activeTab === 'brainhole').toString()"
          @click="activeTab = 'brainhole'"
        >
          脑洞工作台
        </button>
        <button
          class="left-panel-tab"
          :class="{ active: activeTab === 'stages' }"
          type="button"
          role="tab"
          :aria-selected="(activeTab === 'stages').toString()"
          @click="activeTab = 'stages'"
        >
          创作流程
        </button>
        <button
          class="left-panel-tab"
          :class="{ active: activeTab === 'promptControl' }"
          type="button"
          role="tab"
          :aria-selected="(activeTab === 'promptControl').toString()"
          @click="activeTab = 'promptControl'"
        >
          提示词控制
        </button>
        <button
          class="left-panel-tab"
          :class="{ active: activeTab === 'copyBody' }"
          type="button"
          role="tab"
          :aria-selected="(activeTab === 'copyBody').toString()"
          @click="activeTab = 'copyBody'"
        >
          复制正文
        </button>
      </div>

      <div v-if="activeTab === 'brainhole'" class="left-panel-tab-body">
        <div class="left-panel-brainhole-section">
          <BrainholeInputPanel
            :story-start="storyStart"
            :wind-vane-file="windVaneFile"
            :is-loading="isLoading"
            :reference-items="dnaAssetReferences?.brainhole || []"
            :result-reference-items="dnaResultReferences?.brainholeOptions || []"
            :file-text-icon-paths="fileTextIconPaths"
            :show-clear-brainhole="false"
            compact
            @update:story-start="emit('update:storyStart', $event)"
            @choose-wind-vane-file="emit('choose-wind-vane-file')"
            @wind-vane-file-change="emit('wind-vane-file-change', $event)"
            @wind-vane-file-dragover="emit('wind-vane-file-dragover', $event)"
            @wind-vane-file-dragleave="emit('wind-vane-file-dragleave', $event)"
            @wind-vane-file-drop="emit('wind-vane-file-drop', $event)"
            @clear-wind-vane-file="emit('clear-wind-vane-file')"
            @clear-brainhole-input="emit('clear-brainhole-input')"
            @generate-brainhole="emit('generate-brainhole')"
          />
        </div>
      </div>

      <div v-else class="left-panel-tab-body left-panel-tab-body-stages">
        <template v-if="activeTab === 'stages'">
          <div class="left-stage-nav-card">
            <div class="section-title section-title-tight">创作流程</div>
            <StageIndicator
              :stage="stage"
              :active-stage="activeStageView"
              orientation="vertical"
              @navigate="emit('navigate-stage', $event)"
            />
          </div>
        </template>

        <section v-else-if="activeTab === 'promptControl'" class="automation-panel">
          <div class="section-title">提示词控制</div>
          <div class="automation-switch-list">
            <label class="automation-switch-card">
              <input
                :checked="promptAutomationSettings.autoGeneratePlot !== false"
                type="checkbox"
                @change="updatePromptAutomationSetting('autoGeneratePlot', $event)"
              />
              <span class="automation-switch-body">
                <span class="automation-switch-title">自动生成剧情</span>
              </span>
            </label>
            <label class="automation-switch-card">
              <input
                :checked="promptAutomationSettings.autoGenerateChoices !== false"
                type="checkbox"
                @change="updatePromptAutomationSetting('autoGenerateChoices', $event)"
              />
              <span class="automation-switch-body">
                <span class="automation-switch-title">自动生成选项</span>
              </span>
            </label>
            <label class="automation-switch-card">
              <input
                :checked="promptAutomationSettings.generateBodyBeforeChoices !== false"
                type="checkbox"
                @change="updatePromptAutomationSetting('generateBodyBeforeChoices', $event)"
              />
              <span class="automation-switch-body">
                <span class="automation-switch-title">选项前生成正文</span>
              </span>
            </label>
          </div>
        </section>

        <section v-else class="body-record-panel">
          <div class="section-title">复制正文</div>
          <div class="copy-body-tools">
            <button
              class="btn btn-primary btn-sm btn-block"
              type="button"
              :disabled="!canCopyBody"
              @click="emit('copy-body')"
            >
              复制正文
            </button>
            <label class="copy-choice-toggle">
              <input
                :checked="copySelectedChoicesWithBody"
                type="checkbox"
                @change="updateCopySelectedChoicesWithBody"
              />
              <span>复制选项</span>
            </label>
          </div>

          <div class="copy-preview-panel">
            <div class="copy-preview-header">
              <span>将复制到剪切板</span>
              <span>{{ copyBodyPreviewText.length }} 字</span>
            </div>
            <pre v-if="copyBodyPreviewText" class="copy-preview-text">{{ copyBodyPreviewText }}</pre>
            <div v-else class="copy-preview-empty">暂无可复制正文</div>
          </div>
        </section>
      </div>
    </div>
  </aside>
</template>

// src/react/components/EditorLeftPanel.jsx
import { useState } from 'react';
import BrainholeInputPanel from './BrainholeInputPanel.jsx';
import StageIndicator from './StageIndicator.jsx';

export default function EditorLeftPanel({
  isCollapsed = false,
  storyStart = '',
  windVaneFile = null,
  isLoading = false,
  dnaAssetReferences = { brainhole: [], guide: [], outline: [] },
  dnaResultReferences = { brainholeOptions: [], guide: [], architecture: [] },
  stage = 'brainhole',
  activeStageView = 'brainhole',
  fileTextIconPaths = [],
  canCopyBody = false,
  promptAutomationSettings = {
    autoGeneratePlot: true,
    autoGenerateChoices: true,
    generateBodyBeforeChoices: true,
  },
  copySelectedChoicesWithBody = false,
  copyBodyPreviewText = '',
  onTogglePanel,
  onUpdateStoryStart,
  onChooseWindVaneFile,
  onWindVaneFileChange,
  onWindVaneFileDragover,
  onWindVaneFileDragleave,
  onWindVaneFileDrop,
  onClearWindVaneFile,
  onClearBrainholeInput,
  onGenerateBrainhole,
  onNavigateStage,
  onUpdatePromptAutomationSetting,
  onCopyBody,
  onUpdateCopySelectedChoicesWithBody,
}) {
  const [activeTab, setActiveTab] = useState('brainhole');

  return (
    <aside className={`panel panel-left${isCollapsed ? ' collapsed' : ''}`}>
      <button
        className="panel-toggle"
        type="button"
        aria-expanded={(!isCollapsed).toString()}
        aria-label={isCollapsed ? '展开左侧区域' : '折叠左侧区域'}
        onClick={onTogglePanel}
      >
        <svg className="panel-toggle-icon" viewBox="0 0 20 20" aria-hidden="true">
          {isCollapsed ? <path d="M7.5 4.5 13 10l-5.5 5.5" /> : <path d="M12.5 4.5 7 10l5.5 5.5" />}
        </svg>
      </button>

      {isCollapsed ? (
        <div className="panel-collapsed-hint" />
      ) : (
        <div className="panel-body">
          <div className="left-panel-tabs" role="tablist" aria-label="左侧功能区">
            {[
              ['brainhole', '脑洞工作台'],
              ['stages', '创作流程'],
              ['promptControl', '提示词控制'],
              ['copyBody', '复制正文'],
            ].map(([tabKey, label]) => (
              <button
                key={tabKey}
                className={`left-panel-tab${activeTab === tabKey ? ' active' : ''}`}
                type="button"
                role="tab"
                aria-selected={(activeTab === tabKey).toString()}
                onClick={() => setActiveTab(tabKey)}
              >
                {label}
              </button>
            ))}
          </div>

          {activeTab === 'brainhole' ? (
            <div className="left-panel-tab-body">
              <div className="left-panel-brainhole-section">
                <BrainholeInputPanel
                  storyStart={storyStart}
                  windVaneFile={windVaneFile}
                  isLoading={isLoading}
                  referenceItems={dnaAssetReferences?.brainhole || []}
                  resultReferenceItems={dnaResultReferences?.brainholeOptions || []}
                  fileTextIconPaths={fileTextIconPaths}
                  showClearBrainhole={false}
                  compact
                  onUpdateStoryStart={onUpdateStoryStart}
                  onChooseWindVaneFile={onChooseWindVaneFile}
                  onWindVaneFileChange={onWindVaneFileChange}
                  onWindVaneFileDragover={onWindVaneFileDragover}
                  onWindVaneFileDragleave={onWindVaneFileDragleave}
                  onWindVaneFileDrop={onWindVaneFileDrop}
                  onClearWindVaneFile={onClearWindVaneFile}
                  onClearBrainholeInput={onClearBrainholeInput}
                  onGenerateBrainhole={onGenerateBrainhole}
                />
              </div>
            </div>
          ) : (
            <div className="left-panel-tab-body left-panel-tab-body-stages">
              {activeTab === 'stages' ? (
                <div className="left-stage-nav-card">
                  <div className="section-title section-title-tight">创作流程</div>
                  <StageIndicator
                    stage={stage}
                    activeStage={activeStageView}
                    orientation="vertical"
                    onNavigate={onNavigateStage}
                  />
                </div>
              ) : null}

              {activeTab === 'promptControl' ? (
                <section className="automation-panel">
                  <div className="section-title">提示词控制</div>
                  <div className="automation-switch-list">
                    {[
                      ['autoGeneratePlot', '自动生成剧情'],
                      ['autoGenerateChoices', '自动生成选项'],
                      ['generateBodyBeforeChoices', '选项前生成正文'],
                    ].map(([key, label]) => (
                      <label key={key} className="automation-switch-card">
                        <input
                          checked={promptAutomationSettings[key] !== false}
                          type="checkbox"
                          onChange={(event) => onUpdatePromptAutomationSetting?.(key, event.target.checked)}
                        />
                        <span className="automation-switch-body">
                          <span className="automation-switch-title">{label}</span>
                        </span>
                      </label>
                    ))}
                  </div>
                </section>
              ) : null}

              {activeTab === 'copyBody' ? (
                <section className="body-record-panel">
                  <div className="section-title">复制正文</div>
                  <div className="copy-body-tools">
                    <button
                      className="btn btn-primary btn-sm btn-block"
                      type="button"
                      disabled={!canCopyBody}
                      onClick={onCopyBody}
                    >
                      复制正文
                    </button>
                    <label className="copy-choice-toggle">
                      <input
                        checked={copySelectedChoicesWithBody}
                        type="checkbox"
                        onChange={(event) => onUpdateCopySelectedChoicesWithBody?.(event.target.checked)}
                      />
                      <span>复制选项</span>
                    </label>
                  </div>
                  <div className="copy-preview-panel">
                    <div className="copy-preview-header">
                      <span>将复制到剪切板</span>
                      <span>{copyBodyPreviewText.length} 字</span>
                    </div>
                    {copyBodyPreviewText ? (
                      <pre className="copy-preview-text">{copyBodyPreviewText}</pre>
                    ) : (
                      <div className="copy-preview-empty">暂无可复制正文</div>
                    )}
                  </div>
                </section>
              ) : null}
            </div>
          )}
        </div>
      )}
    </aside>
  );
}
